name: 构建和部署GitBook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 安装GitBook CLI
      run: |
        npm install -g gitbook-cli
        
    - name: 安装依赖
      run: |
        gitbook install
        
    - name: 构建GitBook
      run: |
        gitbook build
        
    - name: 部署到GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        force_orphan: true
